### ISSUE TITLE
Apex Not work with dotnet 8

### ISSUE THREAD

**Issue by mbtolou** [dbolin/Apex.Serialization#222]
Hi.

Apex Not work with dotnet core 8!

**Comment by mbtolou** [comment]
```
   at System.Linq.Expressions.Expression.RequiresCanWrite(Expression expression, String paramName)
   at System.Linq.Expressions.Expression.Assign(Expression left, Expression right)
   at Apex.Serialization.Internal.Reflection.FieldInfoModifier..cctor() in E:\TEMP\benchmark\Apex.Serialization-master\Apex.Serialization\Internal\Reflection\FieldInfoModifier.cs:line 40
```

exception detail!

**Comment by mbtolou** [comment]
thanks.
